# Generated by Django 5.1.7 on 2025-06-08 14:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Опис')),
                ('date_published', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публікації')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news_images/', verbose_name='Зображення')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Новина',
                'verbose_name_plural': 'Новини',
                'ordering': ['-date_published'],
            },
        ),
    ]
